Repository dy102/thinker, pull requests merged in 2024-01, with the labels that each got.

#3 Feature/#1 로그인 기능 구현
  server/src/main/java/com/example/thinker/config/SwaggerConfig.java
  server/src/main/java/com/example/thinker/constants/ErrorConst.java
  server/src/main/java/com/example/thinker/constants/SessionConst.java
  server/src/main/java/com/example/thinker/controller/MemberController.java
  server/src/main/java/com/example/thinker/domain/Grade.java
  server/src/main/java/com/example/thinker/domain/Image.java
  server/src/main/java/com/example/thinker/domain/Member.java
  server/src/main/java/com/example/thinker/domain/Thinking.java
  server/src/main/java/com/example/thinker/dto/MemberSimpleDto.java
  server/src/main/java/com/example/thinker/dto/request/MemberDataRequest.java
  server/src/main/java/com/example/thinker/dto/response/MemberDataResponse.java
  server/src/main/java/com/example/thinker/exception/GeneralExceptionHandler.java
  server/src/main/java/com/example/thinker/repository/ImageRepository.java
  server/src/main/java/com/example/thinker/repository/MemberRepository.java
  server/src/main/java/com/example/thinker/service/ImageService.java
  server/src/main/java/com/example/thinker/service/ImageServiceImpl.java
  server/src/main/java/com/example/thinker/service/MemberService.java
  server/src/main/java/com/example/thinker/service/MemberServiceImpl.java
  server/src/main/java/com/example/thinker/util/Convertor.java
  server/src/test/java/com/example/thinker/service/ImageServiceImplTest.java
  server/src/test/java/com/example/thinker/service/MemberServiceImplTest.java
Labels: Feature, 백엔드

#5 #2 폴더 정리
  client/.eslintrc.json
  client/.gitignore
  client/README.md
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/public/next.svg
  client/public/vercel.svg
  client/src/app/favicon.ico
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/app/page.tsx
  client/tailwind.config.ts
  client/tsconfig.json
Labels: Feature, 프론트엔드

#7 헤더 UI제작
  client/package-lock.json
  client/package.json
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/app/page.tsx
  client/src/components/Button/Button.tsx
  client/src/components/Layout/FullLayout.tsx
  client/src/components/Layout/Header.style.tsx
  client/src/components/Layout/Header.tsx
  client/src/components/Layout/page.style.tsx
  client/src/components/PageLink/PageLink.tsx
Labels: Feature, 프론트엔드

#9 Refactor/#4 member api
  server/image/person.jpeg
  server/src/main/java/com/example/thinker/controller/MemberController.java
  server/src/main/java/com/example/thinker/domain/Image.java
  server/src/main/java/com/example/thinker/domain/Member.java
  server/src/main/java/com/example/thinker/dto/response/MemberDataDto.java
  server/src/main/java/com/example/thinker/dto/response/MemberDataResponse.java
  server/src/main/java/com/example/thinker/repository/ImageRepository.java
  server/src/main/java/com/example/thinker/service/ImageService.java
  server/src/main/java/com/example/thinker/service/ImageServiceImpl.java
  server/src/main/java/com/example/thinker/service/MemberService.java
  server/src/main/java/com/example/thinker/service/MemberServiceImpl.java
  server/src/main/java/com/example/thinker/util/Convertor.java
  server/src/test/java/com/example/thinker/service/ImageServiceImplTest.java
  server/src/test/java/com/example/thinker/service/MemberServiceImplTest.java
  server/src/test/resources/data.sql
  server/src/test/resources/static/image/person.jpeg
Labels: refactor, Feature, 백엔드

#11 마이페이지(프로필카드) UI제작
  client/next.config.js
  client/src/app/layout.tsx
  client/src/app/mypage/changeInfo/changeInfo.style.tsx
  client/src/app/mypage/changeInfo/page.tsx
  client/src/app/mypage/mypage.style.tsx
  client/src/app/mypage/page.tsx
  client/src/app/mypage/profileImg.jpg
  client/src/app/mypage/record/page.tsx
  client/src/app/mypage/record/record.style.tsx
  client/src/components/Button/Button.tsx
  client/src/components/Button/IconButton.tsx
  client/src/components/Layout/Footer.style.tsx
  client/src/components/Layout/Footer.tsx
  client/src/components/Layout/FullLayout.tsx
  client/src/components/Layout/Header.style.tsx
  client/src/components/Layout/Header.tsx
  client/src/components/PageLink/PageLink.tsx
  client/src/components/Themes/color.ts
Labels: Feature, 프론트엔드

#13 로그인 회원가입 UI제작
  client/src/app/globals.css
  client/src/app/logIn/page.tsx
  client/src/app/mypage/changeInfo/changeInfo.style.tsx
  client/src/app/signIn/page.tsx
  client/src/app/signIn/signIn.style.tsx
  client/src/components/Button/Button.tsx
  client/src/components/Layout/Footer.style.tsx
  client/src/components/Layout/Header.tsx
  client/src/components/Themes/color.ts
Labels: Feature, 프론트엔드

#15 메인 페이지UI 제작
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/src/api/index.ts
  client/src/api/thinkingPremium-api.ts
  client/src/app/collect/CollectArray.tsx
  client/src/app/mypage/mypage.style.tsx
  client/src/app/mypage/page.tsx
  client/src/app/page.tsx
  client/src/app/survey/page.tsx
  client/src/app/thinking/page.tsx
  client/src/components/Layout/FullLayout.tsx
  client/src/components/Layout/Header.style.tsx
  client/src/components/Layout/Header.tsx
  client/src/components/Layout/Mainpage.style.tsx
  client/src/components/Layout/page.style.tsx
  client/src/components/Premium/PremiumSurvey/PremiumSurvey.style.tsx
  client/src/components/Premium/PremiumSurvey/PremiumSurvey.tsx
  client/src/components/Premium/PremiumThinking/PremiumSurvey.style.tsx
  client/src/components/Premium/PremiumThinking/PremiumThinking.tsx
  client/src/components/Toast/Toast.tsx
  client/src/components/types/common.ts
  client/src/components/types/dto.ts
  server/src/main/java/com/example/thinker/dto/response/MemberDataResponse.java
Labels: Feature, 프론트엔드
