Repository dy102/thinker, pull requests merged in 2024-02, with the labels that each got.

#19 thinking 모아보기 페이지
  client/package-lock.json
  client/package.json
  client/src/api/index.ts
  client/src/api/thinking-api.ts
  client/src/api/thinkingPremium-api.ts
  client/src/app/collect/CollectArray.tsx
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/app/page.tsx
  client/src/app/premium_thinking.jpg
  client/src/app/thinking/page.tsx
  client/src/components/Layout/Mainpage.style.tsx
  client/src/components/Layout/ReactQueryProviders.tsx
  client/src/components/Layout/page.style.tsx
  client/src/components/Normal/NormalThinking/NormalThinking.style.tsx
  client/src/components/Normal/NormalThinking/NormalThinking.tsx
  client/src/components/Normal/NormalThinking/NormalThinkingCollect.tsx
  client/src/components/Premium/PremiumThinking/PremiumThinking.style.tsx
  client/src/components/Premium/PremiumThinking/PremiumThinking.tsx
  client/src/components/collect/PremiumSurveyCollect.tsx
  client/src/components/collect/PremiumThinkingCollect.tsx
  client/src/components/types/common.ts
  client/src/components/types/dto.ts
Labels: Feature, 프론트엔드

#21 게시물보기 페이지 UI제작
  client/src/api/collect-api.ts
  client/src/api/index.ts
  client/src/api/reply-api.ts
  client/src/api/thinking-api.ts
  client/src/api/userInfo-api.ts
  client/src/app/mypage/mypage.style.tsx
  client/src/app/page.tsx
  client/src/app/signIn/page.tsx
  client/src/app/survey/page.tsx
  client/src/app/thinking/[thinkingId]/ThinkingImage.tsx
  client/src/app/thinking/[thinkingId]/page.tsx
  client/src/app/thinking/page.tsx
  client/src/components/Normal/NormalThinking/NormalThinking.style.tsx
  client/src/components/Normal/NormalThinking/NormalThinking.tsx
  client/src/components/Normal/NormalThinking/NormalThinkingCollect.tsx
  client/src/components/Premium/PremiumSurvey/PremiumSurvey.tsx
  client/src/components/Premium/PremiumThinking/PremiumThinking.style.tsx
  client/src/components/Premium/PremiumThinking/PremiumThinking.tsx
  client/src/components/Reply/Reply.tsx
  client/src/components/collect/PremiumThinkingCollect.tsx
  client/src/components/collect/Survey/PremiumSurveyCollect.tsx
  client/src/components/collect/Thinking/NormalThinkingCollect.tsx
  client/src/components/collect/Thinking/PremiumThinkingCollect.tsx
  client/src/components/types/common.ts
  client/src/components/types/dto.ts
Labels: Feature, 프론트엔드

#23 Feature/#18 설문조사 api
  server/build.gradle
  server/src/main/java/com/example/thinker/config/QuerydslConfig.java
  server/src/main/java/com/example/thinker/controller/SurveyController.java
  server/src/main/java/com/example/thinker/controller/ThinkingController.java
  server/src/main/java/com/example/thinker/domain/Choice.java
  server/src/main/java/com/example/thinker/domain/ChoiceForm.java
  server/src/main/java/com/example/thinker/domain/MultipleChoiceForm.java
  server/src/main/java/com/example/thinker/domain/Subjective.java
  server/src/main/java/com/example/thinker/domain/SubjectiveForm.java
  server/src/main/java/com/example/thinker/domain/Survey.java
  server/src/main/java/com/example/thinker/dto/ItemDto.java
  server/src/main/java/com/example/thinker/dto/MultipleChoiceDto.java
  server/src/main/java/com/example/thinker/dto/MultipleChoiceRequestDto.java
  server/src/main/java/com/example/thinker/dto/SubjectiveDto.java
  server/src/main/java/com/example/thinker/dto/SubjectiveRequestDto.java
  server/src/main/java/com/example/thinker/dto/SurveyDetailDto.java
  server/src/main/java/com/example/thinker/dto/SurveyDto.java
  server/src/main/java/com/example/thinker/dto/SurveyDtos.java
  server/src/main/java/com/example/thinker/dto/SurveyRequestDtos.java
  server/src/main/java/com/example/thinker/dto/request/SurveyMakeRequest.java
  server/src/main/java/com/example/thinker/dto/response/PremiumSurveysResponse.java
  server/src/main/java/com/example/thinker/dto/response/SurveyDataResponse.java
  server/src/main/java/com/example/thinker/dto/response/SurveysResponse.java
  server/src/main/java/com/example/thinker/dto/response/ThinkingResponse.java
  server/src/main/java/com/example/thinker/repository/ChoiceFormRepository.java
  server/src/main/java/com/example/thinker/repository/ChoiceRepository.java
  server/src/main/java/com/example/thinker/repository/MultipleChoiceFormRepository.java
  server/src/main/java/com/example/thinker/repository/SubjectiveFormRepository.java
  server/src/main/java/com/example/thinker/repository/SubjectiveRepository.java
  server/src/main/java/com/example/thinker/repository/SurveyRepository.java
  server/src/main/java/com/example/thinker/repository/ThinkingRepository.java
  server/src/main/java/com/example/thinker/service/MemberServiceImpl.java
  server/src/main/java/com/example/thinker/service/SurveyService.java
  server/src/main/java/com/example/thinker/service/SurveyServiceImpl.java
  server/src/main/java/com/example/thinker/service/ThinkingService.java
  server/src/main/java/com/example/thinker/service/ThinkingServiceImpl.java
  server/src/main/java/com/example/thinker/util/Convertor.java
  server/src/test/java/com/example/thinker/service/SurveyServiceImplTest.java
Labels: Feature, 백엔드

#25 feat: reply API 추가, queryDsl 설정 삭제
  server/build.gradle
  server/src/main/java/com/example/thinker/config/QuerydslConfig.java
  server/src/main/java/com/example/thinker/constants/ErrorConst.java
  server/src/main/java/com/example/thinker/controller/MemberController.java
  server/src/main/java/com/example/thinker/controller/ReplyController.java
  server/src/main/java/com/example/thinker/controller/SurveyController.java
  server/src/main/java/com/example/thinker/controller/ThinkingController.java
  server/src/main/java/com/example/thinker/domain/Reply.java
  server/src/main/java/com/example/thinker/domain/ReplyLike.java
  server/src/main/java/com/example/thinker/dto/ReplyDto.java
  server/src/main/java/com/example/thinker/dto/ReplyDtos.java
  server/src/main/java/com/example/thinker/dto/response/RepliesResponse.java
  server/src/main/java/com/example/thinker/repository/ReplyLikeRepository.java
  server/src/main/java/com/example/thinker/repository/ReplyRepository.java
  server/src/main/java/com/example/thinker/service/ReplyService.java
  server/src/main/java/com/example/thinker/service/ReplyServiceImpl.java
  server/src/main/java/com/example/thinker/service/ThinkingServiceImpl.java
Labels: Feature, 백엔드

#29 fix: image 오류 수정
  server/src/main/java/com/example/thinker/controller/MemberController.java
  server/src/main/java/com/example/thinker/controller/ThinkingController.java
  server/src/main/java/com/example/thinker/dto/request/ThinkingRequest.java
  server/src/main/java/com/example/thinker/service/ImageServiceImpl.java
  server/src/main/java/com/example/thinker/service/SurveyServiceImpl.java
  server/src/main/java/com/example/thinker/service/ThinkingService.java
  server/src/main/java/com/example/thinker/service/ThinkingServiceImpl.java
Labels: 백엔드, Fix
